apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  labels:
    app: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: kong:2.8.1
          command: ["/bin/bash"]
          args: ["/scripts/wrapper.sh"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /usr/local/kong/template.yml
              subPath: template.yml
            - name: wrapper
              mountPath: /scripts
          env:
            - name: KONG_STATUS_LISTEN
              value: "0.0.0.0:8100"
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: "/usr/local/kong/kong.yml"
            - name: KONG_DNS_ORDER
              value: "LAST,A,CNAME"
            - name: KONG_PLUGINS
              value: "request-transformer,cors,key-auth,acl,basic-auth"
            - name: KONG_NGINX_PROXY_PROXY_BUFFER_SIZE
              value: "160k"
            - name: KONG_NGINX_PROXY_PROXY_BUFFERS
              value: "64 160k"
            - name: DASHBOARD_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dashboard
                  key: username
            - name: DASHBOARD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dashboard
                  key: password
            - name: SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: anonKey
            - name: SUPABASE_SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: serviceKey
      volumes:
        - name: config
          configMap:
            name: kong-config
            defaultMode: 0777
            items:
              - key: template.yml
                path: template.yml
        - name: wrapper
          configMap:
            name: kong-config
            defaultMode: 0777
            items:
              - key: wrapper.sh
                path: wrapper.sh
