apiVersion: v1
kind: Secret
metadata:
  name: db
type: Opaque
data:
{{- range $key, $value := .Values.secret.db }}
{{- if $value }}
{{- if or (eq (typeOf $value) "string") (eq (typeOf $value) "numeric") }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- end }}
  password_encoded: {{ .Values.secret.db.password | urlquery | b64enc }}
