apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vector-reader
rules:
  - apiGroups: [""]
    resources: ["nodes", "namespaces", "pods"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    resourceNames:
      - "*"
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vector-view
subjects:
  - kind: ServiceAccount
    name: vector-sa
    namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: vector-reader
  apiGroup: rbac.authorization.k8s.io
