apiVersion: apps/v1
kind: Deployment
metadata:
  name: meta
  labels:
    app: meta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meta
  template:
    metadata:
      labels:
        app: meta
    spec:
      containers:
        - name: meta
          image: supabase/postgres-meta:v0.80.0
          ports:
            - containerPort: 8080
          env:
            - name: PG_META_DB_USER
              value: "supabase_admin"
            - name: PG_META_PORT
              value: "8080"
            - name: PG_META_DB_HOST
              value: db-rw
            - name: PG_META_DB_PORT
              value: "5432"
            - name: PG_META_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db
                  key: database
            - name: PG_META_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db
                  key: password
