apiVersion: v1
kind: Service
metadata:
  # service name must be equal to  tenant external id [ex:- realtime-dev]
  name: realtime-dev
spec:
  selector:
    app: realtime
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
